spring.application.name=jbank

# CONFIG PARA BD EM MEMORIA (H2) alterar ao utilizar SGBD (POSTGRESQL OU MYSQL)
spring.datasource.url=jdbc:h2:mem:jbank
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=bd
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true